"""tabela acao

Revision ID: 902b0ea11ccb
Revises: a79370f9afd6
Create Date: 2025-12-14 09:50:52.409169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902b0ea11ccb'
down_revision: Union[str, Sequence[str], None] = 'a79370f9afd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jardim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('REGA', 'PODA', 'ADUBO', 'OUTOR', name='tipoacao'), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['planta_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('planta_usuario', sa.Column('jardim', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planta_usuario', 'jardim', ['jardim'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planta_usuario', type_='foreignkey')
    op.drop_column('planta_usuario', 'jardim')
    op.drop_table('acao')
    op.drop_table('jardim')
    # ### end Alembic commands ###
